### ISSUE TITLE
`select` option for queries

### ISSUE THREAD

**Issue by brenoliradev** [posva/pinia-colada#111]
Hey! Just a feature request for: https://tanstack.com/query/latest/docs/framework/react/guides/render-optimizations#select

I'm on my way to building features to use `pinia-colada` on my project on the future instead of `vue-query` so I'll work in this. Just creating the issue so we can discuss it here too.

**Comment by posva** [comment]
I'm actually not a big fan of `select`, I don't think it's needed for Vue because the 

> This is useful for highly optimized data transformations or to avoid unnecessary re-renders.

doesn't apply.

I would personally just write that logic within the `query` function. I'm open to changing my mind of course.
