### ISSUE TITLE
Pinia with version 2.2.0 is required

### ISSUE THREAD

**Issue by sabel8** [posva/pinia-colada#126]
I tried to use the package for my project, however after a weird issue in the console and some time looking into the issue, I found that my error is probably due to a feature missing in my version of Pinia (2.0.26) and seems like that feature is [added in 2.2.0](https://github.com/vuejs/pinia/blob/v2/packages/pinia/CHANGELOG.md#220-2024-07-26). The `action` helper was added to `defineStore`.

The error I was getting:
`Uncaught TypeError: Cannot destructure property 'action' of 'undefined' as it is undefined.`
![image](https://github.com/user-attachments/assets/ecc2d25d-0ef7-4d76-8914-a66aadf8a00b)

The related code snippet:
![image](https://github.com/user-attachments/assets/193bcf44-01dc-408b-8e6a-be11e996b737)

**Comment by posva** [comment]
I thought I had specified this in peerDeps but clearly not.
Upgrade pinia and you are good to go 🙂
