### ISSUE TITLE
feat: add async/await support to useQuery

### ISSUE THREAD

**Issue by YoSev** [posva/pinia-colada#127]
Feature request: add async/await support to useQuery to enable fetching synchronously.

I know this defeats the purpose of state management (thus the whole project) a bit but it would be nice to use the caching layer while fetching data synchronously.

**Comment by posva** [comment]
It doesn't defeat the purpose of the library 😄 . I think it makes sense if you want to use it with suspense. You can then just await the refresh() call:

```ts
const { data, refresh } = useQuery({ /* ... */ })
await refresh()
```

I haven't tried it thought, but it should work. In practice I would actually go for [data loaders](https://uvr.esm.is/data-loaders/) instead of Suspense

**Comment by NoeReverse** [comment]
Another way to utilize the caching layer is to manipulate the Query Cache. You can access the Query Cache using the  `useQueryCache` composable. You can check for the presence of data by the key using `queryCache.getQueryData(key)`, and if the data is not in the cache, run a query and add it there using `queryCache.setQueryData(key, data)`. You can create a separate composable for this purpose. 

However, it would be very good to have this feature in the library.

**Comment by posva** [comment]
Or you can just call refresh 😄

**Comment by YoSev** [comment]
Thank you guys. I think this library could indeed need sync support.
For now, i went for awaiting the refresh:
`  const res = useQuery({
    key: k.value,
    staleTime: ttl !== undefined ? ttl : 0,
    enabled: false,
    query: () => method(params)
  })
  await res.refresh()`
