### ISSUE TITLE
Introducing focus manager and online manager

### ISSUE THREAD

**Issue by Mini-ghost** [posva/pinia-colada#13]
Currently, every time `useQuery` is called, it registers callbacks for the `visibilitychange` and `online` events (if `options.refetchOnWindowFocus` or `options.refetchOnReconnect` are set to `true`).

Could we consider the introduction of a focus manager and online manager mechanism? This approach would allow us to manage subscriptions to changes in focus and online status uniformly, rather than registering new events each time.

**Comment by posva** [comment]
What problem are you trying to solve? The way events are registered is an implementation detail

**Comment by Mini-ghost** [comment]
Currently, each invocation of `useQuery` registers an independent `visibilitychange` and `online` event. If there are many instances of `useQuery` used on a page, this leads to numerous registrations of the same events.

By utilizing an `onlineManager`, we can register the `visibilitychange` and `online` events just once and create a list to collect callbacks from all queries.

Below is a simplified example to illustrate this approach:

```typescript
class Manager {
  #listeners: Set<() => void>

  constructor() {
    this.#listeners = new Set()
    window.addEventListener('visibilitychange', this.#handleVisibilityChange)
    window.addEventListener('online', this.#handleOnline)
  }

  #handleVisibilityChange = () => {
    if (document.visibilityState === 'visible') {
      this.#listeners.forEach(listener => listener())
    }
  }

  #handleOnline = () => {
    this.#listeners.forEach(listener => listener())
  }
}
```

I am not certain if this approach aligns with your expectations, but I would be very pleased to understand any considerations you might have.

**Comment by posva** [comment]
But what problem are you trying to solve? Is this just speculation?

**Comment by Mini-ghost** [comment]
My initial thought was to manage all event callbacks through a central hub. This way, we could execute `window.addEventListener(event, callback)` just once, instead of on every `useQuery`.

Let me try to explain my idea in more detail.

Currently, each `useQuery` sets up its own event listener. So, if there are multiple `useQuery` instances on a page, each event triggers its own `callback` and decides whether to `refresh`. This means if there are 10 `useQuery` instances, the event would trigger 10 `callbacks`.

Moreover, if there are two identical `useQuery` instances (i.e., with the same `key`), even though the current design ensures `refresh` is executed only once, the `callback` still runs twice.

It would be great if the `callback` could run just once!

We might add a `refresh` method to `queryEntry`. When an `online` or `visibilitychange` event occurs, the event's `callback` could iterate over all `queryEntry` in `cachesRaw` and execute the `refresh` method.

This way, the `callback` needs to run only once, and since `refresh` is specific to each `queryEntry`, there's no need to worry about duplicate calls.

I'm not sure if my idea covers everything, so I wanted to share and discuss it with everyone. Thank you for your time and feedback.

**Comment by posva** [comment]
I think this is a premature optimization and I’m unsure if there would be any positive impact from refactoring this. A document usually handles hundreds to thousands of events. The amount of time use query is active per page is rarely above 10. So I don’t think this will create any issue but I’m happy to reconsider if proven wrong

**Comment by Mini-ghost** [comment]
I think you are right, thanks for your feedback
