### ISSUE TITLE
Add a `key` option to mutations that is optional

### ISSUE THREAD

**Issue by posva** [posva/pinia-colada#16]
This will allow later on to retrieve mutation state, cancel ongoing mutations etc. By default mutations have no key and cannot be "reused"

**Comment by ElisePatrikainen** [comment]
Should the mutation key option have the same type as the query key option (apart from the fact it is optional)? If yes, should we create a mutualized type (`UseKey` for example, which would be used for mutation and query keys)?

**Comment by posva** [comment]
yeah, it could be mutualized into an EntryKey
