### ISSUE TITLE
Gc timeout is not triggered in the context of a query declared with the `defineQuery` composable

### ISSUE THREAD

**Issue by ElisePatrikainen** [posva/pinia-colada#32]
It seems that the `removeDep` function is not called in the context of a query declared with the `defineQuery` composable. More precisely, the [`onScopeDispose`](https://github.com/posva/pinia-colada/blob/main/src/use-query.ts#L155) hook seems not to be called.

Not sure if it is relevant, but I noticed that the scopes are not the same for a query declared with the `useQuery` composable and the `defineQuery` composable.

In the `useQuery` context:

<img width="1483" alt="Capture d’écran 2024-04-21 à 19 15 21" src="https://github.com/posva/pinia-colada/assets/30713720/5e587a3b-77d9-492f-9f54-029ed5d43666">

And in the `defineQuery` context:

<img width="1501" alt="Capture d’écran 2024-04-21 à 18 56 10" src="https://github.com/posva/pinia-colada/assets/30713720/3a8ab842-5d99-4137-9317-ab4fe6098b21">

_Note: I will provide later the demo of these two cases._

**Comment by posva** [comment]
Nice catch. The funny part is that I wrote down this initially but forgot to implement it. There are cases where both, onUnmounted and onScopeDispose need to be used to work correctly. For globals like stores, the entry will never be gc collected until the key changes.
