### ISSUE TITLE
Add a query filter

### ISSUE THREAD

**Issue by ElisePatrikainen** [posva/pinia-colada#36]
It could be interesting to have a way to filter queries when we look for some specific queries in the cache (a usecase could be the `useQueriesState` composable, cf https://github.com/posva/pinia-colada/issues/23).

For example, here is the query filter provided by TanStack Query : https://tanstack.com/query/latest/docs/framework/react/guides/filters#query-filters

**Comment by posva** [comment]
Yes, this would be nice and needed for retrieving some shared state

**Comment by posva** [comment]
This is now possible with `.getEntries()`. The resulting entries can be passed to individual methods instead of duplicating methods
