### ISSUE TITLE
Implement `enabled` option in `useQuery()` to control the automatic querying

### ISSUE THREAD

**Issue by posva** [posva/pinia-colada#42]
This will controll the initial fetching and also any automatic refetching like refetchOnFocus, refetchOnMount. There should be a way for this to be reachable by plugins so a `refetchInterval` can be implemented but still controlled by this option.
It should allow a ref or getter too and immediately refresh if going from false to true

**Comment by quiteeasy** [comment]
I have added an initial implementation for the requested feature. However, this implementation may need further adjustments once the `refetchInterval` functionality is introduced.

The current implementation focuses on the core functionality, but it may need to be updated to ensure seamless integration with the `refetchInterval` feature once that functionality is available.

I would appreciate it if you could review the current implementation and provide any feedback or suggestions. Once the `refetchInterval` functionality is introduced, we can revisit this implementation and make the necessary adjustments to ensure compatibility.

Please let me know if you have any questions or concerns about this approach.
