### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by posva** [posva/pinia-colada#5]
- Quick Start
  - Installation
  - Introduction
  - Playsink
- Guides
  - Queries
  - Query keys
  - Cache and refreshing data
  - Mutations
  - Optimistic updates
    - UI
    - Cache
- Plugins
- Cookbook

**Comment by ElisePatrikainen** [comment]
Hi, I can do it. 

I can write a page in `docs/guide` per point (with the optimistic updates empty for now). Should we add a guide on how to use the queries with the Pinia Colada data loaders (from the Unplugin Vue Router)?

**Comment by posva** [comment]
We can split this up into multiple pages for the guide about all of the main concepts. An introduction/quick started to show the main benefits (e.g. useQuery, cache + invalidation)
data loaders are still experimental so it's better to keep them in uvr
