### ISSUE TITLE
Add a placeholder data option

### ISSUE THREAD

**Issue by minht11** [posva/pinia-colada#57]
Loading spinners are bad, it less disruptive to show users previous data until new data is ready. Suspense is somewhat based on that idea.

Have code like this:
```ts
const { data } = useQuery({
	key: () => ['item', props.selectedItemId],
	query: () => getItemById(props.selectedItemId),
})
```
when props.selectedItemId changes current behavior of useQuery forces me to show blank screen because data does not exist, I wish data would not be reset while isFetching is true.

**Comment by posva** [comment]
It’s normal it’s not kept by default. But maybe a placeholder option could add this
