### ISSUE TITLE
[Queries] Synchronous errors in the query function are not caught

### ISSUE THREAD

**Issue by ElisePatrikainen** [posva/pinia-colada#69]
Let's take for example the following query, with a typo in the query function which leads to a synchronous error:
``` js
const { data } = useQuery({
  key: () => ['items', route.params.id],
  query: () => {
    const id = routeZ.params.id  // Typo here, `routeZ` is undefined
    return fetch(id)
  }
})
```
When the query is ran, the error is not passed to the relevant `catch` block, and the query remains in a `loading` state. 

For information, as soon as this error is made asynchronous, the error is caught and the query is set to the `error` state as usual:
```js
const { data } = useQuery({
  key: () => ['items', route.params.id],
  query: async () => {
    const id = await routeZ.params.id // The error is made asynchronous => it is caught and the query state updated
    return fetch(id)
  }
})
```

**Comment by posva** [comment]
Yeah, i noticed while testing. I think this is fine because only async methods make sense and the function shouldn’t throw unexpected errors, only reject.

**Comment by posva** [comment]
For DX, we could maybe catch this during dev only though

**Comment by ElisePatrikainen** [comment]
I agree, that would be useful to log it in dev mode.

Alternatively, here is a try/proposition to directly handle synchronous errors (it makes the code less elegant though): https://github.com/posva/pinia-colada/pull/70

**Comment by minht11** [comment]
This would be very unintuitive for the regular users, if error is handled in some cases and not in others, from my own codebase I have few cases like:
```ts
query: (to) => getData(Number(to.params.id)),
```
getData returns a promise so it itself is safe, but imagine if I had some validation for `id` which throws an error, popular with `zod` type of libraries, this is just waiting for production issues to happen.
