### ISSUE TITLE
Q: vue-apollo Apollo Cache

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [posva/pinia-colada#8]
So, when fetching with the apollo client all the fetched data lands in the normalized cache of apollo. Would there be any benefit in using pinia-colada or pinia in general to do the fetching other that maybe global availability, which would not be in issue since requests are cached anyway.

**Comment by posva** [comment]
At first sight I would say not. This is because Apollo already acts as data fetching layer. The current main advantage is [Data Loaders](https://uvr.esm.is/rfcs/data-loaders/)
