### ISSUE TITLE
[BUG] Not compatible with pinia ^2.1

### ISSUE THREAD

**Issue by Hanmo123** [posva/pinia-colada#87]
Pinia Colada destructs `action` variable in the file below:

https://github.com/posva/pinia-colada/blob/2fc62b76e9c2ffcac1f7331f0ab7a1098d6e2fd8/src/query-store.ts#L263

while pinia ^2.1 has no parameter defined:

![QQ_1728790848910](https://github.com/user-attachments/assets/cb66dfa9-e832-4e02-a5cb-5b9d00ec3c7d)

in pinia ^2.2, helpers are added:

![QQ_1728790897752](https://github.com/user-attachments/assets/1a8f60ff-1ead-48c0-9bbf-b9a352c9748b)

**Comment by posva** [comment]
Yes, you need an up to date pinia version
