### ISSUE TITLE
Keep getting `"getActivePinia()" was called but there was no active Pinia` error

### ISSUE THREAD

**Issue by ymansurozer** [posva/pinia-colada#93]
I wanted to give Pinia Colada a try because it really looks great!

But immediately after I do the setup and try to use `useQuery`, I get the error in the title. I am not calling Pinia anywhere at all and the stack shows it is being called in Colada. I have a very simple `app.vue`:

```ts
<script lang="ts" setup>
import type { Todo } from '~/types';
import { useQuery } from '@pinia/colada';

const newTodo = ref('');

const { data: todos } = useQuery({
  key: ['todos'],
  query: () => $fetch<Todo[]>('/api/todos'),
});
</script>

<template>
  <div>
    <div>
      <input v-model="newTodo" />
    </div>

    <h2>Todos</h2>
    <pre>{{ todos }}</pre>
  </div>
</template>

```

Here is a reproduction: https://stackblitz.com/edit/github-xmm1oh?file=app.vue

**Comment by posva** [comment]
See https://github.com/vuejs/pinia/issues/2820

**Comment by posva** [comment]
There are a few issues related to Nuxt (or vite) and deps. I recommend you to add `@pinia/colada` to the exclude array alongside pinia too 🙂 
That warning is fixed but not released yet. it's just that, a warning that shouldn't be shown. It's also only about HMR, so dev only. Nothing to worry.

**Comment by posva** [comment]
FYI, the latest `@pinia/nuxt` module should fix the issue

**Comment by ymansurozer** [comment]
Thank you very much Eduardo!
